### PR TITLE
strengthens systemd copy : Create destination directory first.

### PR DESCRIPTION
**Pull request by braoult**
related to [#33](https://github.com/JSubelj/g910-gkey-macro-support/issues/33). 
https://stackoverflow.com/questions/1529946/linux-copy-and-create-destination-dir-if-it-does-not-exist

### CODE REVIEW

**Comment by JSubelj** [comment]
Whilst this could be a better way I think the install should fail, if the /usr/lib/systemd/system does not exist. That's because something is probably wrong and needs users input. We don't want to make decisions for the user. In the case of #33 it was probably that because Ubuntu uses /lib/systemd/system, user thought the installer overrode the folder. I say for now the installer should fail if the folder does not exist. In the future, installer must be expended to choose exactly were it should place the service file depending on the distro.

**Comment by braoult** [comment]
In Ubuntu, /usr/lib/systemd/system is the correct one.

**Comment by braoult** [comment]
Sorry, my mistake:
https://unix.stackexchange.com/questions/206315/whats-the-difference-between-usr-lib-systemd-system-and-etc-systemd-system/458252#458252

/usr/lib/systemd/system is *NOT* used on debian based distro ubuntu.
On a fresh install, this directory is *not* created (dpkg-query -L systemd shows it).

**Comment by braoult** [comment]
> Whilst this could be a better way I think the install should fail, if the /usr/lib/systemd/system does not exist. That's because something is probably wrong and needs users input. We don't want to make decisions for the user. In the case of #33 it was probably that because Ubuntu uses /lib/systemd/system, user thought the installer overrode the folder. I say for now the installer should fail if the folder does not exist. In the future, installer must be expended to choose exactly were it should place the service file depending on the distro.

OK. I did submit a new patch, keeping full path of file as you did, but using system-dependent paths instead of hardcoded one. At least  @bcvery1 case would be covered.

**Pull request closed without merging**
