### PR TITLE
m key support and profile switching. Closes #14

### LINKED ISSUE #14: [Feature] 3 config files for the 3 M keys
so i was wondering if it is Possible to add a config for each M key, cause i would like to be able to switch profile. so like m1-config.json and m2 and m3.

### PR DESCRIPTION
**Pull request by MR-R080T**
Provides support for M keys and allows any G or M key to switch the active config file

### CODE REVIEW

**Comment by JSubelj** [comment]
Hey,

great work! I would just like to comment on some things:

- Switching the color of logo:
I do understand that some sort of indication would be nice but not everyone wants to get their color changed depending on the config type. I would propose using `notify-send` command to notify the user about the change.

- Involvement of g810-led program:
 g810-led is not a dependency and I removed it, so that users don't need to have it and can use some other led changing program. If the program is not installed on the system then errors are logged, but not having a g810-led installed is not an error. I would propose checking if g810-led exists on the system and checking in the config or someway if the user really wants this behavior.

- Changing logo to breathing: 
Why not just turn on/off m1-3/mr lights to the corresponding config/keypress?

- Naming the configs:
I would propose some sort of config naming inside the config. Currently, if you open the config.json, you can't really tell which config is used, is it m1 or mr or which. Having a `config_name` property in json file would resolve that and also you could send a `notify-send` command with the message: "Configuration changed to $config_name".

- Changing readme.md:
You did great with documenting the feature, but merging it would mean I would have to change the source git and delete the first line. It's not a bother to do that but it would be easier for me to just merge the pull request without editing it :)

Again you did really great work and thank you for that. If you could fix the commented parts I would be glad to merge your pull request. 

Would love to hear from you,

Jan

**Comment by bcourtine** [comment]
Since I like this PR, I worked on it. I changed the notification system to switch mX led if `g910-leds` is available.

Here is the code: https://github.com/bcourtine/g910-gkey-macro-support/tree/swap-config
I can create a new PR if it is good for you.

PS: sorry for the code quality. I am not used to develop in Python.

**Comment by ModProg** [comment]
> Since I like this PR, I worked on it. I changed the notification system to switch mX led if `g910-leds` is available (instead of colorizing the logo).
> 
> Here is the code: https://github.com/bcourtine/g910-gkey-macro-support/tree/swap-config
> I can create a new PR if it is good for you.
> 
> PS: sorry for the code quality. I am not used to develop in Python.

 MR-R080T  does not seam to be active on GitHub anymore, so I think you should open a new PullRequest so this has a chance of being merged at all.

**Comment by suabo** [comment]
I kind of picked that one up in #60 and added profile switching with a single config.json.
Give it a try

**Pull request closed without merging**
