### PR TITLE
added support for mkey macros

### PR DESCRIPTION
**Pull request by hbregalad**
I as much i could, I preserved to the structure and style of your code. Even though I don't entirely understand what you're doing in gkey_functionality.py

### CODE REVIEW

**Comment by suabo** [comment]
First of all thank you for your pull request.  
Since the profile switching feature I added in #60 gives you up to 28 macro key options and this implementation of the mkeys only allow for a total of 13 i tend to decline this pull request and close it.
It would be possible to add this feature in addition, but for me it don't adds any value anymore.
Maybe you can try the profile feature and tell me what you think about it?

**Comment by hbregalad** [comment]
Cool! I'm glad to see active maintenance again! :)

Yes, I like the design of #60. I was doing profile switching via executing command with significantly more risk of typos.
Also, I'd like to note that, if profiles switching isn't limited to only m keys, and default profile names, you don't need to be limited to 28 macros, but to as much of a finite state machine as you choose to build and can map/navigate in your head. :D

**Comment by suabo** [comment]
I thought about it, but since i can't even remember all my mapped gkeys there was no reason for me going this way.  
But thinking it through it would be nice to add mkeys to config and implement some helper methods to choose the profile (load, first, before, after, last). This way you could also switch a profile with a gkey instead of mkey. Indication of profiles via mkey leds can only work with constant profile names, but that's okay. This would be the trade of to have more then four profiles.
I don't feel the need for that right now. Maybe if someone request to be able to have more profiles I will have another look at this.

**Comment by hbregalad** [comment]
:) yeah, I only use like 8 macros, and I only want them partitioned off into separate profiles for ergonomics reasons.

**Pull request closed without merging**
